version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=eu-west-3
      - DEBUG=1
      - DYNAMODB_SHARE_DB=1
    volumes:
      - "./localstack:/var/lib/localstack"
