version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=eu-west-3
      - DEBUG=1
      - DYNAMODB_SHARE_DB=1
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform
    volumes:
      - "../infra:/app"
    working_dir: /app
    entrypoint: /bin/sh -c "terraform init && terraform apply -auto-approve"
    depends_on:
      - localstack
